config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/before_login', to: 'static_pages#before_login'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  resource :user, only: %i[new create]
  resource :profile, only: %i[new show edit update]
  resource :reminder_time, only: %i[new create]
  resources :activity_images, only: %i[index new create]
  resources :activity_records, only: %i[index edit update destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    if current_user.nil?
      render 'top'
    else
      redirect_to activity_records_path
    end
  end

  def before_login
    if current_user.nil?
      render 'before_login'
    else
      redirect_to activity_records_path
    end
  end

  def terms; end

  def privacy; end

  def after_login
    login_required
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/before_login.html.erb
<div class="container py-3">
  <div class="jumbotron">
    <h1 class="p-3 mb-2 bg-light">ログインできない場合はブラウザで開き直してください</h1>
    <br>
    <div class='text-center'>
      <%= link_to '（LINE）ユーザー登録・ログイン', new_user_path, class: 'btn btn-success btn-lg', target: '_blank' %>
    </div>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<div class="container pt-3">
  <h3 class="text-center">プライバシーポリシー</h3>
  <div class="m-4">
  <p>
    本ウェブサイトの管理者（以下，「管理者」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，お客様の個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
  </p>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">お客様から取得する情報</h5>
  <p>当社は、お客様から以下の情報を取得します。</p>
    <ul>
        <li class= "mb-1">氏名（ニックネームやペンネーム含む）</li>
        <li class= "mb-1">外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
        <li class= "mb-1">Cookie（クッキー）を用いて生成された識別情報</li>
        <li class= "mb-1">本ウェブサイトの滞在時間、入力履歴等の本ウェブサイトにおけるお客様の行動履歴</li>
    </ul>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">個人情報の利用目的</h5>
  <p>本サービスは、お客様から取得した情報を利用する目的は以下のとおりです。</p>
    <ul>
      <li class= "mb-1">本サービスに関する登録の受付、お客様の本人確認、認証のため</li>
      <li class= "mb-1">お客様の本サービスの利用履歴を管理するため</li>
      <li class= "mb-1">本サービスにおけるお客様の行動履歴を分析し、本サービスの維持改善に役立てるため</li>
      <li class= "mb-1">お客様からのお問い合わせに対応するため</li>
      <li class= "mb-1">本サービスの利用規約や法令に違反する行為に対応するため</li>
      <li class= "mb-1">本サービスの変更、提供中止、終了、契約解除を連絡するため</li>
      <li class= "mb-1">本サービス規約の変更等を通知するため</li>
      <li class= "mb-1">以上の他、管理者サービスの提供、維持、保護及び改善のため</li>
    </ul>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">第三者提供</h5>
    <p class="mt-2">
    当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第2条第6項）に該当するものについては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。
    </p>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">アクセス解析ツール</h5>
    <p class="mt-2">
    お客様からお預かりした個人情報を、個人情報保護法その他の法令に基づき開示が認められる場合を除き、お客様ご本人の同意を得ずに第三者に提供することはありません。
    </p>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">プライバシーポリシーの変更</h5>
  <p>
  プライバシーポリシーの内容を適宜見直し、その改善に努めます。<br>
  内容の変更は、当サイトに掲載された時点で有効になるものとします。
  </p>
  </div>

  <div class="m-4">
  <h5 class="text-decoration-underline">お問合せ</h5>
  <p class="mt-2">お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のお問合せフォーム先のアカウントにDMでご連絡ください。<br>
  <%=link_to "お問い合わせ", "https://twitter.com/Rz0Bp", class: "mt-2 link-dark" %>
  </p>
  </div>

  <div class="m-4">
  <p>2023年02月12日制定</p>
  </div>
</div>

app/views/static_pages/terms.html.erb
<div class="container pt-3">
  <h3 class="text-center">利用規約</h3>

  <div class="m-4">
  <p>
    この利用規約（以下、「本規約」といいます。）は、本ウェブサイトの管理者（以下、「管理者」といいます。）がこのウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。
    ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。
  </p>
  </div>

  <div class="m-4">
  <h5>第1条（適用）</h5>
    <ol>
        <li class= "mb-1">本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
        <li class= "mb-1">当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。</li>
        <li class= "mb-1">本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第2条（利用登録）</h5>
    <ol>
        <li class= "mb-1">本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</li>
        <li class= "mb-1">当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</li>
        <p>・本規約に違反したことがある者からの申請である場合<br>
        ・その他，当社が利用登録を相当でないと判断した場合
        </p>
    </ol>
  </div>

  <div class="m-4">
  <h5>第3条（ユーザーIDおよびパスワードの管理）</h5>
    <ol>
        <li class= "mb-1">ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。</li>
        <li class= "mb-1">ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</li>
        <li class= "mb-1">ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第4条（利用料金および支払方法）</h5>
    <ol>
        <li class= "mb-1">ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</li>
        <li class= "mb-1">ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第5条（禁止事項）</h5>
    <ol>
        <li class= "mb-1">法令または公序良俗に違反する行為</li>
        <li class= "mb-1">犯罪行為に関連する行為</li>
        <li class= "mb-1">本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為/li>
        <li class= "mb-1">当社，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
        <li class= "mb-1">本サービスによって得られた情報を商業的に利用する行為</li>
        <li class= "mb-1">当社のサービスの運営を妨害するおそれのある行為</li>
        <li class= "mb-1">不正アクセスをし，またはこれを試みる行為</li>
        <li class= "mb-1">他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li class= "mb-1">不正な目的を持って本サービスを利用する行為</li>
        <li class= "mb-1">本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為</li>
        <li class= "mb-1">他のユーザーに成りすます行為</li>
        <li class= "mb-1">当社が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為</li>
        <li class= "mb-1">面識のない異性との出会いを目的とした行為</li>
        <li class= "mb-1">当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li class= "mb-1">その他，当社が不適切と判断する行為</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第6条（本サービスの提供の停止等）</h5>
    <ol>
        <li class= "mb-1">当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
        <p class="mt-1">
        ・本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br>
        ・地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合<br>
        ・コンピュータまたは通信回線等が事故により停止した場合<br>
        ・その他，当社が本サービスの提供が困難と判断した場合<br>
        </p>
        <li class= "mb-1">当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第7条（利用制限および登録抹消）</h5>
    <ol>
        <li class= "mb-1">当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。</li>
        <p class="mt-1">
        ・本規約のいずれかの条項に違反した場合<br>
        ・当社からの連絡に対し，一定期間返答がない場合<br>
        ・本サービスについて，最終の利用から一定期間利用がない場合<br>
        ・その他，当社が本サービスの利用を適当でないと判断した場合<br>
        </p>
        <li class= "mb-1">当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第8条（保証の否認および免責事項）</h5>
    <ol>
        <li class= "mb-1">当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
        <li class= "mb-1">当社は，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</li>
        <li class= "mb-1">前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
        <li class= "mb-1">当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</li>
    </ol>
  </div>

  <div class="m-4">
  <h5>第9条（サービス内容の変更等）</h5>
    <p class= "mb-1">当社は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。</p>
  </div>

  <div class="m-4">
  <h5>第10条（利用規約の変更）</h5>
    <p class= "mb-1">当社は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。</p>
    <p class= "mb-1">・本規約の変更がユーザーの一般の利益に適合するとき。<br>
    ・本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。
    </p>
    <p class= "mb-1">当社はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。</p>
  </div>

  <div class="m-4">
  <h5>第11条（個人情報の取扱い）</h5>
    <p class= "mb-1">当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
  </div>

  <div class="m-4">
  <h5>第12条（通知または連絡）</h5>
    <p class= "mb-1">ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
  </div>

  <div class="m-4">
  <h5>第13条（権利義務の譲渡の禁止）</h5>
    <p class= "mb-1">ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
  </div>

  <div class="m-4">
  <h5>第14条（準拠法・裁判管轄）</h5>
    <ol>
        <li class= "mb-1">本規約の解釈にあたっては，日本法を準拠法とします。</li>
        <li class= "mb-1">本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
    </ol>
  </div>

  <div class="m-4">
  <p>2023年02月12日制定</p>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="top-wrapper">
  <div class="top-about text-center center-block py-5">
    <h1 class="pb-2 app_title">RFA_Record</h1>
    <h4 class="pb-2 app_title">リングフィットアドベンチャーを<br>継続したい方へ</h4>
  </div>
  <div class="top-about center-block bg-light py-5">
    <div class="col-lg-6 offset-lg-3 mt-2">
      <h3 class="text-center mb-4 border-bottom pb-3">「RFA_Record」とは</h3>
      <p class="px-5 text-center">「RFA_Record」とは、リングフィットアドベンチャーの活動を記録できるアプリです!</p>
      <p class="px-5 text-center">「RFA_Record」は、写真を送信するだけで簡単に活動が記録、グラフ化することができます!</p>
    </div>
  </div>
  <div class="top-content center-block pt-5 pb-3">
    <div class="col-lg-6 offset-lg-3 mt-2">
      <h3 class="text-center mb-4 border-bottom pb-3">使い方</h3>
      <div class="card mb-5 p-5">
      <h4 class="text-center card-title mb-3 border-bottom pb-3">友達追加しよう！</h4>
      <p class='text-center'><b><font color="green">「RFA_Record」を友達追加、LINE認証</font>してRFAをする準備を整えましょう！</b><br>
      メールアドレスやパスワードの入力が不要なので、スムーズに登録が行えます!</p>
      <div class="text-center mb-3">
        <a href="https://lin.ee/ZuNoyMr"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
      </div>
      </div>
      <div class="card mb-5 p-5">
        <h4 class="text-center card-title mb-3 border-bottom pb-3">1. 投稿しよう！</h4>
        <p class='text-center'><b><font color="#ff0000">「写真投稿」</font> から写真を投稿しよう！</b><br>
          活動記録の写真投稿をすると自動的に文字データを抽出し<br>編集画面を表示いたします！
          <br>
          <br>
          <b><font color="#66cc66">写真を撮る</font></b>
          <%= image_tag 'record.webp', size: '300x200', class: 'mx-auto d-block' %>
          <i class="bi bi-arrow-down-square-fill" style='font-size: 2rem; color: #66cc66;'></i><br>
          <b><font color="#66cc66">写真を送る</font></b>
          <%= image_tag 'push_record.webp', size: '200x300', class: 'mx-auto d-block' %> 
        </p>
      </div>
      <div class="card mb-5 p-5">
        <h4 class="text-center card-title mb-3 border-bottom pb-3">2. データを確認しよう！</h4>
        <p class='text-center'>
          写真から抽出したデータが間違っていないか確認し<br>
          投稿一覧に表示する場合は✅を入れてください！<br>
          問題なければ更新ボタンを押してください！
        </p>
        <%= image_tag 'edit_record.webp', size: '200x300', class: 'mx-auto d-block' %> 
      </div>
      <div class="card mb-5 p-5">
        <h4 class="text-center card-title mb-3 border-bottom pb-3">3. 投稿を見てみよう！</h4>
        <p class='text-center'>
          投稿一覧から自分や他の人の活動記録を見ることができます！<br>
          他の人の投稿を見てRFAのモチベを上げていきましょう！
        </p>
        <%= image_tag 'edit_record.webp', size: '200x300', class: 'mx-auto d-block' %> 
      </div>
      <div class="card mb-5 p-5">
        <h4 class="text-center card-title mb-3 border-bottom pb-3">4. グラフを見てみよう！</h4>
        <p class='text-center'>
          グラフを押してプロフィール画面を表示してみましょう！<br>
          今までの活動記録をグラフとして見ることができます！
        </p>
        <%= image_tag 'graph_record.webp', size: '200x300', class: 'mx-auto d-block' %> 
      </div>
      <div class="card mb-2 p-5">
        <h4 class="text-center card-title mb-3 border-bottom pb-3">友達追加して早速使ってみる</h4>
        <div class="text-center">
          <a href="https://lin.ee/ZuNoyMr"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
        </div>
      </div>
    </div>
  </div>
</div>