config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/before_login', to: 'static_pages#before_login'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  resource :user, only: %i[new create]
  resource :profile, only: %i[new show edit update]
  resource :reminder_time, only: %i[new create]
  resources :activity_images, only: %i[index new create]
  resources :activity_records, only: %i[index edit update destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[new edit update]
  before_action :login_required, only: %i[new show edit update]

  def new
    @activity_records = @user.activity_records.order(created_at: :desc).page(params[:page])
  end

  def show
    @records = current_user.activity_records.order(:act_date).pluck(:act_date, :act_time, :act_calories, :act_distance)
    @weekly_records = current_user.activity_records.where('act_date >= ?', 1.week.ago).order(:act_date).pluck(
      :act_date, :act_time, :act_calories, :act_distance
    )
    @monthly_records = current_user.activity_records.where('act_date >= ?', 1.month.ago).order(:act_date).pluck(
      :act_date, :act_time, :act_calories, :act_distance
    )
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:nickname, :avatar, :avatar_cache, :twitter_url, :introduction)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 pt-2 bg-light">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user, url: profile_path, local: true do |f| %>
        <%= render "shared/error_messages", object: f.object %>
          <div class="form-group">
            <%= f.label :nickname %>
            <%= f.text_field :nickname, class: "form-control mb-3" %>
          </div>
          <div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class: "form-control",
                              accept: 'image/*',
                              onchange: 'previewImage(preview)' %>
            <%= f.hidden_field :avatar_cache %>
            <div class='mt-3 mb-3'>
              <%= image_tag @user.avatar.url, id: 'preview',
                                              size: '100x100',
                                              class: 'rounded-circle' %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :twitter_url %>
            <%= f.text_field :twitter_url, class: "form-control mb-3" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_field :introduction, class: "form-control mb-3" %>
          </div>
          <div class="actions mb-2">
            <%= f.submit t('defaults.update') %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container pt-3">
  <!-- 投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @activity_records.present? %>
          <%= render partial: 'activity_records/record', collection: @activity_records, as: :activity_record %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <%= paginate @activity_records %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container pt-2">
  <div class="row">
    <div class="col-md-10 my-2 bg-light offset-md-1">
      <h1 class="float-left"><%= t('.title') %></h1><br>
      <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success float-right' %>
      <table class="table">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:nickname) %></th>
          <td>
            <% if current_user.nickname.present? %>
              <%= current_user.nickname %>
            <% else %>
              <%= current_user.name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:avatar) %></th>
          <td><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:twitter_url) %></th>
          <td><%= link_to current_user.twitter_url do %>
            <i class="bi bi-twitter"></i>
          <% end %>
          </td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:introduction) %></th>
          <td><%= current_user.introduction %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:reminder_time) %></th>
          <td><%= current_user.reminder_time.strftime('%H:%M') if current_user.reminder_time %></td>
        </tr>
      </table>
      <div class='text-center'>
        <%= link_to new_profile_path do %>
          <button class='btn btn-info'>個人の活動記録</button>
        <% end %>
      </div>
      <br>
      
      <button onclick="loadChartData('overall')">全体</button>
      <button onclick="loadChartData('weekly')">週間</button>
      <button onclick="loadChartData('monthly')">月間</button>

      <canvas id="myChart"></canvas>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
      <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart;

        function loadChartData(timeInterval) {
          var records;
          if (timeInterval === 'weekly') {
            records = <%= @weekly_records.to_json.html_safe %>;
          } else if (timeInterval === 'monthly') {
            records = <%= @monthly_records.to_json.html_safe %>;
          } else {
            records = <%= @records.to_json.html_safe %>;
          }

          updateChart(records);
        }

        function updateChart(records) {
          if (myChart) {
            myChart.destroy();
          }

          var chartData = {
            labels: records.map(function(record) {
              return record[0];  // 日付を取得
            }),
            datasets: [
              {
                label: '活動時間',
                data: records.map(function(record) {
                  return record[1];
                }),
                backgroundColor: 'rgba(255, 99, 132, 0.2)',
                borderColor: 'rgba(255, 99, 132, 1)',
                yAxisID: 'y-axis-1'
              },
              {
                label: '消費カロリー',
                data: records.map(function(record) {
                  return record[2];
                }),
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderColor: 'rgba(54, 162, 235, 1)',
                yAxisID: 'y-axis-2'
              },
              {
                label: '走行距離',
                data: records.map(function(record) {
                  return record[3];
                }),
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                yAxisID: 'y-axis-3'
              }
            ]
          };

          myChart = new Chart(ctx, {
            type: 'line',
            data: chartData,
            options: {
              scales: {
                x: {
                  type: 'time',
                  time: {
                    unit: 'day',
                    displayFormats: {
                      day: 'yy/MM/dd'
                    },
                    parser: function(value){
                      return new Date(value);
                    }
                  }
                },
                'y-axis-1': {
                  position: 'left',
                  ticks: {
                    callback: function(value, index, values) {
                      const minutes = Math.floor(value / 60);
                      const seconds = value % 60;
                      return minutes + '分' + seconds + '秒';
                    }
                  }
                },
                'y-axis-2': {
                  position: 'right',
                  ticks: {
                    callback: function(value, index, values) {
                      return value.toFixed(2) + 'kcal';
                    }
                  }
                },
                'y-axis-3': {
                  position: 'right',
                  ticks: {
                    callback: function(value, index, values) {
                      return value.toFixed(2) + 'km';
                    }
                  }
                }
              }
            }
          });
        }
        loadChartData('overall');
        </script>

      <br>
    </div>
  </div>
</div>