config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/before_login', to: 'static_pages#before_login'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  resource :user, only: %i[new create]
  resource :profile, only: %i[new show edit update]
  resource :reminder_time, only: %i[new create]
  resources :activity_images, only: %i[index new create]
  resources :activity_records, only: %i[index edit update destroy]
end

app/models/activity_record.rb
class ActivityRecord < ApplicationRecord
  belongs_to :user
  belongs_to :activity_image

  validates :act_date, presence: true
  validates :act_time, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 86_400 }
  validates :act_calories, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :act_distance, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :comment, length: { maximum: 20 }

  def self.create_new_record(image, extracted_info, current_user)
    act_time = extracted_info[:min] * 60 + extracted_info[:sec]
    act_date = Date.today
    act_calories = extracted_info[:kcal]
    act_distance = extracted_info[:km]

    activity_record = ActivityRecord.new(
      act_date:,
      act_time:,
      act_calories:,
      act_distance:,
      user_id: current_user.id,
      activity_image_id: image.id
    )

    activity_record.save ? activity_record : nil
  end
end

app/controllers/activity_records_controller.rb
class ActivityRecordsController < ApplicationController
  def index
    @activity_records = ActivityRecord.where(visible: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit
    @activity_record = ActivityRecord.find(params[:id])
  end

  def update
    @activity_record = ActivityRecord.find(params[:id])

    if @activity_record.update(activity_record_params)
      redirect_to activity_records_path, success: t('record.update')
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: ActivityRecord.model_name.human)
      render :edit, status: :see_other
    end
  end

  def destroy
    @activity_record = current_user.activity_records.find(params[:id])
    @activity_record.destroy!
    redirect_to activity_records_path, danger: t('record.destroy'),
                                       status: :see_other
  end

  private

  def activity_record_params
    params.require(:activity_record).permit(:act_date, :act_time, :act_calories, :act_distance, :comment, :visible)
  end
end

app/helpers/activity_records_helper.rb
module ActivityRecordsHelper
end

app/views/activity_records/_crud_menus.html.erb
<ul class="crud-menu-btn list-inline" style="float: right">
  <li class="list-inline-item">
    <%= link_to "Share", "https://twitter.com/intent/tweet?url=https://rfa-record.onrender.com/activity_records&text=#{activity_record.act_date}のRFAの活動記録です。
                                    %0A 活動時間：#{activity_record.act_time / 60}分#{activity_record.act_time % 60}秒
                                    %0A 消費kcal：#{activity_record.act_calories}kcal
                                    %0A 走行距離：#{activity_record.act_distance}km
                                    %0A&hashtags=RFA_Record", class: 'btn btn-dark btn-sm', target: '_blank' %>
  </li>
  <li class="list-inline-item">
    <%= link_to '編集', edit_activity_record_path(activity_record), id: 'button-edit-#{activity_record.id}' %>
  </li>
  <li class="list-inline-item">
    <%= button_to '削除', activity_record_path(activity_record), method: :delete, form: { data: { turbo_confirm: t('defaults.confirm') } } %>
  </li>
</ul>

app/views/activity_records/_record.html.erb
<div class="col-sm-12 col-lg-4 mb-3 grow-on-hover">
  <div class="mb-3 border p-4 bg-light">
    <div class="card p-3">
      <p>活動日程: <%= activity_record.act_date %></p>
      <p>活動時間: <%= activity_record.act_time / 60 %> 分 <%= activity_record.act_time % 60 %> 秒</p>
      <p>消費kcal: <%= activity_record.act_calories %> kcal</p>
      <p>走行距離: <%= activity_record.act_distance %> km</p>
      <% if activity_record.comment.present? %>
        <p><%= activity_record.comment %></p>
      <% end %>
      <ul class="list-inline">
        <%= image_tag activity_record.user.avatar.url, class: 'rounded-circle', size: '40x40' %>
        <% if activity_record.user.nickname.present? %>
          <%= activity_record.user.nickname %>
        <% else %>
          <%= activity_record.user.name %>
        <% end %>
      </ul>
      <div class="card-body">
        <% if current_user && current_user.own?(activity_record) %>
          <%= render 'activity_records/crud_menus', activity_record: activity_record %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activity_records/edit.html.erb
<div class="container pt-3 col-12">
  <div class="row">
    <div class="col-sm-12 col-lg-4 mb-3 grow-on-hover">
      <div class="border p-4 bg-light">
        <div class="card p-3">
          <%= form_for @activity_record, url: activity_record_path(@activity_record), method: :patch do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field mb-2">
            <%= f.label :act_date %>
            <%= f.date_field :act_date %>
          </div>
          <div class="field mb-2">
            <%= f.label :act_time %>
            <%= f.text_field :act_time %>
          </div>
          <div class="field mb-2">
            <%= f.label :act_calories %>
            <%= f.text_field :act_calories %>
          </div>
          <div class="field mb-2">
            <%= f.label :act_distance %>
            <%= f.text_field :act_distance %>
          </div>
          <div class="field mb-2">
            <%= f.label :comment %>
            <%= f.text_field :comment %>
          </div>
          <div class="field mb-2">
            <%= f.label :visible, '一覧に表示する場合は☑️してください' %>
            <%= f.check_box :visible, checked: @activity_record.visible %>
          </div>
          <div class="actions">
            <%= f.submit t('defaults.update') %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activity_records/index.html.erb
<div class="container pt-3">
  <!-- 投稿一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @activity_records.present? %>
          <%= render partial: 'activity_records/record', collection: @activity_records, as: :activity_record %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <%= paginate @activity_records %>
    </div>
  </div>
</div>