config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/before_login', to: 'static_pages#before_login'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  resource :user, only: %i[new create]
  resource :profile, only: %i[new show edit update]
  resource :reminder_time, only: %i[new create]
  resources :activity_images, only: %i[index new create]
  resources :activity_records, only: %i[index edit update destroy]
end

app/views/shared/_before_login_header.html.erb
<header class="sticky-top" id='page-top'>
  <nav class="navbar navbar-expand-lg bg-dark fixed-top" id="mainNav">
    <%= link_to t('defaults.app_name'), root_path, class: 'navbar-brand text-primary ms-5' %>
    <div class="ms-auto" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center me-3">
        <li class="me-3">
        <a href="https://lin.ee/ZuNoyMr"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_fixed_footer.html.erb
<footer id='fixed-footer' class="fixed-bottom mt-3">
  <nav class='navbar navbar-expand navigation navbar-light bg-light'>
    <div class='container-fluid'>
      <ul class='navbar-nav d-flex justify-content-center main-nav align-items-center w-100'>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to activity_records_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-pen fs-5"></i>
            <%= t('activity_records.index.title') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to new_activity_image_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-send-fill fs-5"></i>
            <%= t('activity_images.new.title') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to profile_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-graph-up fs-5"></i>
            <%= t('profiles.show.graph') %>
          <% end %>
        </li>
        <li class='nav-item flex-grow-1 text-center'>
          <%= link_to new_reminder_time_path, class: 'dropdown-item d-flex flex-column align-items-center' do %>
            <i class="bi bi-calendar-check-fill fs-5"></i>
            <%= '（リマインド）' %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</footer>

app/views/shared/_flash_message.html.erb
<div class='mt-3 bg-light'>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom bg-dark border-top pt-3">
  <div class="container">
    <div class="copyright text-center mb-2">
      <%=link_to t('static_pages.terms.title'), terms_path, class: "px-1 link-light text-decoration-none" %>
      <%=link_to t('static_pages.privacy.title'), privacy_path, class: "px-1 link-light text-decoration-none" %>
      <%=link_to t('static_pages.contact.title'), "https://forms.gle/gQbwH76T5i5CH3zr8", class: "px-1 link-light text-decoration-none" %>
    </div>
    <div class="copyright text-center text-light">
      <a><%= t('defaults.copyright') %></a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="sticky-top" id='page-top'>
  <nav class='navbar navbar-expand-lg bg-dark fixed-top' id="mainNav">
    <div class="container">
      <%= link_to t('defaults.app_name'), root_path, class: 'navbar-brand text-primary' %>

      <div class='d-block d-lg-none'>
        <button class=' btn btn-link' type='button' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
          <%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '40x40' %>
        </button>
        <div class='dropdown-menu dropdown-menu-end text-center'>
          <% if current_user.nickname.present? %>
            <%= current_user.nickname %>
          <% else %>
            <%= current_user.name %>
          <% end %>
          <div class='dropdown-divider'></div>
          <%= link_to t('profiles.show.title'), profile_path, class: 'dropdown-item' %>
        </div>
      </div>

      <div class='collapse navbar-collapse d-none d-lg-block' id='navbarSupportedContent'>
        <ul class='navbar-nav ms-auto me-3 main-nav align-items-center'>
          <li class='nav-item dropdown dropdown-slide'>
            <a href='#' class='nav-link' data-bs-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
              <%= image_tag current_user.avatar.url, class: 'rounded-circle mr15', size: '40x40' %>
            </a>
            <div class='dropdown-menu dropdown-menu-end'>
              <div class='dropdown-item'>
                <% if current_user.nickname.present? %>
                  <%= current_user.nickname %>
                <% else %>
                  <%= current_user.name %>
                <% end %>
              </div>
              <div class='dropdown-divider'></div>
              <%= link_to t('profiles.show.title'), profile_path, class: 'dropdown-item' %>
              <%#= link_to t('defaults.logout'), user_path(@user), data: { turbo_method: :delete }, class: 'dropdown-item' %>
              <%#= link_to t('defaults.back_talk'), 'https://line.me/R/ti/p/@910svtxk', class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>